services:
  dect_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dect_project_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
